#!/usr/bin/env bash

info () {
  printf "  [ \033[00;34m..\033[0m ] $1\n"
}

success () {
  printf "\r\033[2K  [ \033[00;32mOK\033[0m ] $1\n"
}

fail () {
  printf "\r\033[2K  [\033[0;31mFAIL\033[0m] $1\n"
  echo ''
  exit
}

echo ''
info 'Setting up the Vim Configuration of Champions'
info '============================================='
echo ''

info 'Installing Vundle'
info '-----------------'
git clone https://github.com/VundleVim/Vundle.vim.git ~/.vim/bundle/Vundle.vim

info 'Installing plugins and compiling custom spellings'
info '-------------------------------------------------'
if test $(which mvim)
then
  mvim -v "+mkspell ~/.vim/spell/custom.en.utf-8.add" +PluginInstall +qall
fi
if test $(which vim)
then
    vim "+mkspell ~/.vim/spell/custom.en.utf-8.add" +PluginInstall +qall
else
    fail 'mvim or vim not found in path.'j
fi

rm -fr ~/.vim
ln -s ~/src/dot_vim ~/.vim
ln -s ~/src/dot_vim/vimrc ~/.vimrc
ln -s ~/src/dot_vim/gvimrc ~/.gvimrc
mkdir ~/.vim/.backup
mkdir ~/.vim/.tmp


success 'Setup complete. Run vim and enjoy'
